---
version: '2.3'
services:
  syncthing-web:
    image: syncthing/syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=<022>
      - HTTPS_METHOD=nohttps
    volumes:
      - syncthing-config:/config
      - type: bind
        source: .
        target: /data
        bind:
          propagation: shared
    ports:
      - 8384
      - 22000
      - 21027/udp
    restart: unless-stopped
    networks:
      - syncthing



networks:
  syncthing:

volumes:
  syncthing-config:
    driver: local


