---
version: '2.3'
services:
  server:
    cap_add:
     - NET_ADMIN
    network_mode: "host"
    image: openvpn/docker-openvpn
    restart: always
    privileged: true
    volumes:
     - openvpn-data:/etc/openvpn

  pki:
    image: openvpn/docker-openvpn
    restart: unless-stopped
    command: "/bin/bash -c 'trap : TERM INT; (while sleep 3600; do :; done) & wait'"
    networks:
        - openvpn

networks:
  openvpn:

volumes:
  openvpn-data:
    driver: local

